# Generated by Django 5.2.12 on 2026-04-19 11:47

import django.db.models.deletion
import officework.models
from django.conf import settings
from django.db import migrations, models


def _seed_default_group_and_backfill_messages(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    OfficeWorkChatGroup = apps.get_model('officework', 'OfficeWorkChatGroup')
    OfficeWorkChatGroupMember = apps.get_model('officework', 'OfficeWorkChatGroupMember')
    OfficeWorkChatMessage = apps.get_model('officework', 'OfficeWorkChatMessage')

    admins = User.objects.filter(role__in=('super_admin', 'admin_staff'), is_active=True).order_by('id')
    creator = admins.first()
    creator_id = creator.id if creator else None

    group, _ = OfficeWorkChatGroup.objects.get_or_create(
        name='General',
        defaults={'is_active': True, 'created_by_id': creator_id},
    )

    admin_ids = list(admins.values_list('id', flat=True))
    existing_member_ids = set(
        OfficeWorkChatGroupMember.objects.filter(group_id=group.id, user_id__in=admin_ids).values_list('user_id', flat=True)
    )
    OfficeWorkChatGroupMember.objects.bulk_create(
        [
            OfficeWorkChatGroupMember(group_id=group.id, user_id=user_id, added_by_id=creator_id)
            for user_id in admin_ids
            if user_id not in existing_member_ids
        ],
        ignore_conflicts=True,
    )

    OfficeWorkChatMessage.objects.filter(group_id__isnull=True).update(group_id=group.id)


def _noop_reverse_seed_default_group_and_backfill_messages(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('officework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeWorkChatGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Office Work Chat Group Member',
                'verbose_name_plural': 'Office Work Chat Group Members',
                'db_table': 'core_officeworkchatgroupmember',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='officeworkchatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=officework.models.office_work_chat_attachment_upload_to),
        ),
        migrations.AddField(
            model_name='officeworkchatmessage',
            name='attachment_content_type',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='officeworkchatmessage',
            name='attachment_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='officeworkchatmessage',
            name='attachment_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OfficeWorkChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_work_chat_groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Work Chat Group',
                'verbose_name_plural': 'Office Work Chat Groups',
                'db_table': 'core_officeworkchatgroup',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='officeworkchatmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='officework.officeworkchatgroup'),
        ),
        migrations.AddIndex(
            model_name='officeworkchatmessage',
            index=models.Index(fields=['group', '-id'], name='owchat_group_id_idx'),
        ),
        migrations.AddField(
            model_name='officeworkchatgroupmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_work_chat_members_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeworkchatgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='officework.officeworkchatgroup'),
        ),
        migrations.AddField(
            model_name='officeworkchatgroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_work_chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='officeworkchatgroup',
            index=models.Index(fields=['is_active', 'name'], name='owchatgrp_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='officeworkchatgroupmember',
            index=models.Index(fields=['user', 'group'], name='owchatgm_user_group_idx'),
        ),
        migrations.AddIndex(
            model_name='officeworkchatgroupmember',
            index=models.Index(fields=['group', 'created_at'], name='owchatgm_group_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='officeworkchatgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='owchat_group_user_unique'),
        ),
        migrations.RunPython(
            _seed_default_group_and_backfill_messages,
            _noop_reverse_seed_default_group_and_backfill_messages,
        ),
    ]
