# Generated by Django 5.2.12 on 2026-04-19 18:54

import django.db.models.deletion
import officework.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officework', '0003_officeworktask_add_pending_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='officeworktask',
            name='checklist_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='officeworktask',
            name='collaborator_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='officeworktask',
            name='completion_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officeworktask',
            name='completion_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_work_tasks_completion_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeworktask',
            name='completion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officeworktask',
            name='completion_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_work_tasks_completion_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeworktask',
            name='follower_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OfficeWorkTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=officework.models.office_work_task_comment_attachment_upload_to)),
                ('attachment_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_size_bytes', models.BigIntegerField(default=0)),
                ('attachment_content_type', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_work_task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='officework.officeworktask')),
            ],
            options={
                'verbose_name': 'Office Work Task Comment',
                'verbose_name_plural': 'Office Work Task Comments',
                'db_table': 'core_officeworktaskcomment',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['task', 'id'], name='owtaskcomment_task_id_idx'), models.Index(fields=['-created_at'], name='owtaskcomment_created_idx')],
            },
        ),
    ]
