# Generated by Django 5.2.12 on 2026-04-28 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officework', '0004_officeworktask_checklist_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeWorkLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_work_leads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Work Lead',
                'verbose_name_plural': 'Office Work Leads',
                'db_table': 'core_officeworklead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OfficeWorkSharedFile',
        ),
    ]
