# Generated by Django 5.2.12 on 2026-04-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officework', '0005_officeworklead_delete_officeworksharedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeWorkLeadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20, unique=True)),
                ('content', models.TextField(help_text='Use {{customer_name}}, {{contact}}, {{email}}, {{location}}, {{description}} as placeholders')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
