"""Pro User Platform — constants."""


class ProAuditEvent:
    IMPERSONATION_START = 'IMPERSONATION_START'
    IMPERSONATION_END = 'IMPERSONATION_END'
    CLIENT_ACTIVATED = 'CLIENT_ACTIVATED'
    CLIENT_DEACTIVATED = 'CLIENT_DEACTIVATED'
    MAINTENANCE_ENABLED = 'MAINTENANCE_ENABLED'
    MAINTENANCE_DISABLED = 'MAINTENANCE_DISABLED'
    FEATURE_FLAG_CHANGED = 'FEATURE_FLAG_CHANGED'
    ANNOUNCEMENT_CREATED = 'ANNOUNCEMENT_CREATED'
    ANNOUNCEMENT_DELETED = 'ANNOUNCEMENT_DELETED'
    BACKUP_CREATED = 'BACKUP_CREATED'
    BACKUP_DOWNLOADED = 'BACKUP_DOWNLOADED'


class MaintenanceScope:
    GLOBAL = 'GLOBAL'
    PER_CLIENT = 'PER_CLIENT'


class AnnouncementTarget:
    GLOBAL = 'GLOBAL'
    ORGANIZATION = 'ORGANIZATION'
    CLIENT = 'CLIENT'


class FeatureFlagKey:
    IMPORTS = 'IMPORTS'
    EXPORTS = 'EXPORTS'
    SANDBOX = 'SANDBOX'
    MOBILE_ACCESS = 'MOBILE_ACCESS'
    DESKTOP_API = 'DESKTOP_API'
    WORKFLOW = 'WORKFLOW'
    NOTIFICATIONS = 'NOTIFICATIONS'

    ALL = [IMPORTS, EXPORTS, SANDBOX, MOBILE_ACCESS, DESKTOP_API, WORKFLOW, NOTIFICATIONS]


class BackupScope:
    CLIENT = 'CLIENT'
    ORGANIZATION = 'ORGANIZATION'


class BackupStatus:
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
