# Generated by Django 5.2.15 on 2026-06-04 05:07

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('fields', '0002_initial'),
        ('organizations', '0002_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfilter',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='card',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tables.table'),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carduniquevalue',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_values', to='cards.card'),
        ),
        migrations.AddField(
            model_name='carduniquevalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.field'),
        ),
        migrations.AddField(
            model_name='carduniquevalue',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
        migrations.AddIndex(
            model_name='assistantfilter',
            index=models.Index(fields=['assistant', 'table'], name='cards_assis_assista_f1e658_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['organization'], name='cards_card_organiz_7f4f35_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['table'], name='cards_card_table_i_4f26f8_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['status'], name='cards_card_status_534cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['created_at'], name='cards_card_created_591b38_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deleted_at'], name='cards_card_deleted_127196_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='cards_card_data_af09be_gin'),
        ),
        migrations.AddConstraint(
            model_name='carduniquevalue',
            constraint=models.UniqueConstraint(fields=('table', 'field', 'value_hash'), name='unique_card_field_value'),
        ),
    ]
