# Generated by Django 5.2.15 on 2026-06-04 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
        ('organizations', '0002_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['version'], name='cards_card_version_938475_idx'),
        ),
    ]
