# Generated by Django 5.2.15 on 2026-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_cards_card_version_938475_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('DOWNLOADED', 'Downloaded'), ('DELETED', 'Deleted'), ('ACTIVE', 'Active')], default='PENDING', max_length=50),
        ),
    ]
