# Generated by Django 5.2.15 on 2026-06-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reprint_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='total_print_count',
            field=models.IntegerField(default=1),
        ),
    ]
