# Generated by Django 5.2.12 on 2026-05-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_user_role_guestassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropperRelease',
        ),
    ]
