# Generated by Django 5.2.12 on 2026-05-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_user_is_temp_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropperRelease',
        ),
    ]
