# Generated by Django 5.2.10 on 2026-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustedclient',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='cards_count',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='location_state',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='status_badge',
        ),
        migrations.RemoveField(
            model_name='trustedclient',
            name='trusted_since_year',
        ),
        migrations.AlterField(
            model_name='trustedclient',
            name='name',
            field=models.CharField(help_text='School/Company name', max_length=255),
        ),
    ]
