# Generated by Django 5.2.10 on 2026-02-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_trustedclient_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='type',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_duration',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_posted_ago',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_thumbnail',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_views',
        ),
    ]
