# Generated by Django 5.2.10 on 2026-02-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_productcategory_websitestatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
