# Generated by Django 5.2.10 on 2026-02-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_product_delete_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fas fa-folder', help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default categories cannot be deleted')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='item_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('reel', 'Reel')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='videos/Portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL for video/reel items'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Products/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.portfoliocategory'),
        ),
    ]
