# Generated by Django 5.2.10 on 2026-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_portfoliocategory_portfolioitem_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Slider image', upload_to='images/Hero/')),
                ('title', models.CharField(blank=True, help_text='Optional card title (e.g. "Premium Quality")', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Optional card subtitle (e.g. "Trusted by 500+ Schools")', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
