# Generated by Django 5.2.10 on 2026-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_migrate_hero_images_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='bento_size',
            field=models.CharField(choices=[('large', 'Large'), ('normal', 'Normal')], default='normal', help_text='Card size in bento grid', max_length=10),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='is_bento',
            field=models.BooleanField(default=False, help_text='Show in the bento grid section'),
        ),
    ]
