# Generated by Django 5.2.10 on 2026-02-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_set_bento_defaults'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['status'], name='website_con_status_53fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['email_status'], name='website_con_email_s_69be1a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['created_at'], name='website_con_created_c6daa0_idx'),
        ),
    ]
