# Generated by Django 5.2.10 on 2026-02-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_production_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='trustedclient',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active', 'order'], name='website_faq_is_acti_73bacf_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['is_active', 'order'], name='website_fea_is_acti_6bd60f_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliocategory',
            index=models.Index(fields=['is_active', 'order'], name='website_por_is_acti_2087eb_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_active', 'order'], name='website_por_is_acti_fe86a4_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_active', 'is_featured'], name='website_por_is_acti_f28356_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['is_active', 'order'], name='website_ree_is_acti_d62b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active', '-review_date'], name='website_tes_is_acti_632bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='trustedclient',
            index=models.Index(fields=['is_active', 'order'], name='website_tru_is_acti_fc06ae_idx'),
        ),
    ]
