# Generated by Django 5.2.10 on 2026-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_faq_is_active_alter_feature_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
