# Generated by Django 5.2.10 on 2026-02-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_contactsubmission_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='hero_image1',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='hero_image2',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='hero_image3',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='hero_image4',
        ),
    ]
