# Generated by Django 5.2.10 on 2026-03-07 13:38

from django.db import migrations


# Bento layout: slug → (name, icon, bento_size, order)
BENTO_CATEGORIES = [
    ('id-cards',          'ID Cards',          'fas fa-id-card',           'large',  0),
    ('lanyards',          'Lanyards',          'fas fa-ribbon',            'normal', 1),
    ('badges',            'Badges',            'fas fa-id-badge',          'normal', 2),
    ('school-stationery', 'School Stationery', 'fas fa-pencil-ruler',      'normal', 3),
    ('student-diaries',   'Student Diaries',   'fas fa-book',              'wide',   4),
    ('prospectus',        'Prospectus',        'fas fa-scroll',            'wide',   5),
    ('t-shirts',          'T-Shirts',          'fas fa-tshirt',            'normal', 6),
    ('mugs',              'Mugs',              'fas fa-mug-hot',           'normal', 7),
    ('pamphlets',         'Pamphlets',         'fas fa-file-alt',          'normal', 8),
    ('brochures',         'Brochures',         'fas fa-book-open',         'normal', 9),
]

# Extra categories (not in bento, shown in filter bar)
EXTRA_CATEGORIES = [
    ('certificates',   'Certificates',   'fas fa-certificate',           10),
    ('marksheets',     'Marksheets',     'fas fa-file-alt',              11),
    ('fee-cards',      'Fee Cards',      'fas fa-credit-card',           12),
    ('invitations',    'Invitations',    'fas fa-envelope-open-text',    13),
    ('visiting-cards', 'Visiting Cards', 'fas fa-address-card',          14),
    ('others',         'Others',         'fas fa-print',                 15),
]

BENTO_SLUGS = {slug for slug, *_ in BENTO_CATEGORIES}


def forwards(apps, schema_editor):
    Cat = apps.get_model('website', 'PortfolioCategory')

    # Create or update bento categories
    for slug, name, icon, bento_size, order in BENTO_CATEGORIES:
        obj, created = Cat.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name, 'icon': icon, 'order': order,
                'is_default': True, 'is_bento': True, 'bento_size': bento_size,
            },
        )
        if not created:
            obj.is_bento = True
            obj.bento_size = bento_size
            obj.order = order
            obj.is_active = True
            obj.save(update_fields=['is_bento', 'bento_size', 'order', 'is_active'])

    # Create extra categories (not in bento)
    for slug, name, icon, order in EXTRA_CATEGORIES:
        obj, created = Cat.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name, 'icon': icon, 'order': order,
                'is_default': True, 'is_bento': False,
            },
        )
        if not created and obj.is_bento and obj.slug not in BENTO_SLUGS:
            obj.is_bento = False
            obj.order = order
            obj.save(update_fields=['is_bento', 'order'])


def backwards(apps, schema_editor):
    pass  # No-op reverse


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_hero_image_fields'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
