# Generated by Django 5.2.10 on 2026-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_update_bento_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='bento_size',
            field=models.CharField(choices=[('large', 'Large'), ('wide', 'Wide'), ('normal', 'Normal')], default='normal', help_text='Card size in bento grid', max_length=10),
        ),
    ]
