# Generated by Django – manual migration for bento grid layout v2

from django.db import migrations


def forwards(apps, schema_editor):
    Cat = apps.get_model('website', 'PortfolioCategory')

    # 1. Pamphlets → wide, order 4 (takes Student Diaries' slot)
    Cat.objects.filter(slug='pamphlets').update(
        bento_size='wide', order=4, is_bento=True
    )

    # 2. Student Diaries → wide, order 5 (equal width to Pamphlets)
    Cat.objects.filter(slug='student-diaries').update(
        bento_size='wide', order=5, is_bento=True
    )

    # 3. Remove Prospectus, Brochures, T-Shirts, Mugs from bento grid
    Cat.objects.filter(slug__in=['prospectus', 'brochures', 't-shirts', 'mugs']).update(
        is_bento=False
    )

    # 4. Add/update Office Stationery as a large bento card
    Cat.objects.update_or_create(
        slug='office-stationery',
        defaults={
            'name': 'Office Stationery',
            'icon': 'fas fa-briefcase',
            'bento_size': 'large',
            'is_bento': True,
            'is_default': True,
            'is_active': True,
            'order': 6,
        }
    )


def backwards(apps, schema_editor):
    Cat = apps.get_model('website', 'PortfolioCategory')

    # Restore original bento layout
    Cat.objects.filter(slug='pamphlets').update(bento_size='normal', order=8)
    Cat.objects.filter(slug='student-diaries').update(bento_size='wide', order=4)
    Cat.objects.filter(slug__in=['prospectus', 'brochures', 't-shirts', 'mugs']).update(
        is_bento=True
    )
    Cat.objects.filter(slug='prospectus').update(order=5)
    Cat.objects.filter(slug='t-shirts').update(order=6)
    Cat.objects.filter(slug='mugs').update(order=7)
    Cat.objects.filter(slug='brochures').update(order=9)
    Cat.objects.filter(slug='office-stationery').update(is_bento=False)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_portfoliocategory_bento_size'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
