# Generated by Django 5.2.10 on 2026-04-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_delete_trustedclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='reviewer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
    ]
