# Generated by Django 5.2.10 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_testimonial_reviewer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='reviewer_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
