# Generated by Django 5.2.10 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_testimonial_reviewer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='attachment_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/TestimonialAttachments/'),
        ),
    ]
