# Generated by Django 5.2.12 on 2026-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_testimonial_attachment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Custom SEO meta description'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Custom SEO keywords (comma separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title for this category', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='SEO-friendly alt text for the main image', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Custom SEO meta description'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Custom SEO keywords (comma separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title for this product', max_length=255),
        ),
    ]
