# Generated by Django 5.2.12 on 2026-04-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_portfoliocategory_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image_alt_text',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='meta_title',
        ),
    ]
