# Generated by Django 5.2.12 on 2026-04-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_portfoliocategory_meta_description_and_more'),
    ]

    def update_site(apps, schema_editor):
        Site = apps.get_model('sites', 'Site')
        Site.objects.update_or_create(
            id=1,
            defaults={
                'domain': 'adarshbhopal.in',
                'name': 'Adarsh ID Cards'
            }
        )

    operations = [
        migrations.RunPython(update_site),
    ]
