# Generated by Django 5.2.12 on 2026-04-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_update_site_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='phone',
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='phone1',
            field=models.CharField(blank=True, help_text='First phone number with country code e.g. 919876543210', max_length=20),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='phone2',
            field=models.CharField(blank=True, help_text='Second phone number with country code e.g. 919876543211', max_length=20),
        ),
    ]
