# Generated by Django 5.2.12 on 2026-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_businessdetails_phone_businessdetails_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
    ]
