# Generated by Django 5.2.12 on 2026-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_businessdetails_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description override'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description override'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
    ]
