# Generated by Django 5.2.12 on 2026-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_portfoliocategory_meta_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reel',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='working_hours',
        ),
    ]
