# Generated by Django 5.2.12 on 2026-05-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_delete_reel_remove_businessdetails_footer_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='meta_keywords',
        ),
    ]
