# Generated by Django 5.2.12 on 2026-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_portfoliocategory_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Slider image', upload_to='images/Hero/')),
                ('title', models.CharField(blank=True, help_text='Optional card title (e.g. "Premium Quality")', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Optional card subtitle (e.g. "Trusted by 500+ Schools")', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='attachment_image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='reviewer_email',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='reviewer_ip',
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='footer_text',
            field=models.CharField(blank=True, help_text='Custom footer text', max_length=500),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code e.g. 919876543210', max_length=20),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='working_hours',
            field=models.CharField(blank=True, help_text='e.g. Mon-Sat: 9AM - 6PM', max_length=255),
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/Reels/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Instagram reel URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/Reels/')),
                ('views_count', models.CharField(default='1K', help_text='e.g. 12.5K', max_length=20)),
                ('likes_count', models.CharField(default='100', help_text='e.g. 890', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='website_ree_is_acti_d62b7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School/Company name', max_length=255)),
                ('logo', models.ImageField(help_text='School/Company logo (small, transparent preferred)', upload_to='images/Schools/Logos/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trusted Client',
                'verbose_name_plural': 'Trusted Clients',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='website_tru_is_acti_fc06ae_idx')],
            },
        ),
    ]
