# Generated by Django 5.2.12 on 2026-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_delete_heroimage_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_active', '-created_at'], name='website_por_is_acti_015288_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['category', 'is_active', 'order'], name='website_por_categor_5f0a22_idx'),
        ),
    ]
