# Generated by Django 5.2.12 on 2026-05-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_heroimage_remove_businessdetails_linkedin_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrustedClient',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='phone',
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='phone1',
            field=models.CharField(blank=True, help_text='First phone number with country code e.g. 919876543210', max_length=20),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='phone2',
            field=models.CharField(blank=True, help_text='Second phone number with country code e.g. 919876543211', max_length=20),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description override'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description override'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='attachment_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/TestimonialAttachments/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewer_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
