# Generated by Django 5.2.12 on 2026-05-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_portfolioitem_website_por_is_acti_015288_idx_and_more'),
        ('website', '0031_delete_trustedclient_remove_businessdetails_phone_and_more'),
    ]

    operations = [
    ]
