# Generated by Django 5.2.15 on 2026-06-05 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0003_card_cards_card_version_938475_idx'),
        ('fields', '0002_initial'),
        ('organizations', '0002_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=64)),
                ('storage_provider', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='cards.card')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files_created', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='fields.field')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='organizations.organization')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='tables.table')),
            ],
            options={
                'db_table': 'media_file',
            },
        ),
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=50)),
                ('stored_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'media_variant',
            },
        ),
        migrations.CreateModel(
            name='MediaReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_references', to='cards.card')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_references', to='fields.field')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'media_reference',
                'unique_together': {('card', 'field')},
            },
        ),
    ]
