# Generated by Django 5.2.15 on 2026-06-05 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0003_card_cards_card_version_938475_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_histories', to='cards.card')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['card', 'timestamp'], name='workflow_hi_card_id_3bffca_idx'), models.Index(fields=['old_status'], name='workflow_hi_old_sta_812a30_idx'), models.Index(fields=['new_status'], name='workflow_hi_new_sta_5d641b_idx')],
            },
        ),
    ]
