# Generated by Django 5.2.15 on 2026-06-06 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_space', models.BigIntegerField()),
                ('free_space', models.BigIntegerField()),
                ('used_space', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ops_disk_health',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MemoryHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_memory', models.BigIntegerField()),
                ('available_memory', models.BigIntegerField()),
                ('used_memory', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ops_memory_health',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupVerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('backup_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_results', to='pro.backupartifact')),
            ],
            options={
                'db_table': 'ops_backup_verification',
                'ordering': ['-verification_time'],
            },
        ),
    ]
