# Generated by Django 5.2.15 on 2026-06-05 13:40

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('total_organizations', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_tables', models.IntegerField(default=0)),
                ('total_fields', models.IntegerField(default=0)),
                ('total_cards', models.IntegerField(default=0)),
                ('total_imports', models.IntegerField(default=0)),
                ('total_exports', models.IntegerField(default=0)),
                ('total_media', models.IntegerField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('active_sandbox_sessions', models.IntegerField(default=0)),
                ('storage_bytes', models.BigIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'pro_statistics_snapshot',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('CLIENT', 'Client'), ('ORGANIZATION', 'Organization')], max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_sessions', to='organizations.organization')),
            ],
            options={
                'db_table': 'pro_backup_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='pro.backupsession')),
            ],
            options={
                'db_table': 'pro_backup_artifact',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pro_feature_flag',
            },
        ),
        migrations.CreateModel(
            name='ClientFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_overrides', to='pro.featureflag')),
            ],
            options={
                'db_table': 'pro_client_feature_flag',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pro_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pro_impersonation_session',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='pro.impersonationsession')),
            ],
            options={
                'db_table': 'pro_impersonation_audit',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('PER_CLIENT', 'Per Client')], default='GLOBAL', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_modes', to='organizations.organization')),
            ],
            options={
                'db_table': 'pro_maintenance_mode',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('target_type', models.CharField(choices=[('GLOBAL', 'Global'), ('ORGANIZATION', 'Organization'), ('CLIENT', 'Client')], default='GLOBAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizations.organization')),
            ],
            options={
                'db_table': 'pro_announcement',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'target_type'], name='pro_announc_is_acti_0e8509_idx'), models.Index(fields=['is_pinned'], name='pro_announc_is_pinn_43301a_idx'), models.Index(fields=['created_at'], name='pro_announc_created_52867b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='backupsession',
            index=models.Index(fields=['status'], name='pro_backup__status_68739a_idx'),
        ),
        migrations.AddIndex(
            model_name='backupsession',
            index=models.Index(fields=['created_at'], name='pro_backup__created_2df547_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientfeatureflag',
            unique_together={('feature_flag', 'organization')},
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['pro_user', 'is_active'], name='pro_imperso_pro_use_52e286_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['target_user'], name='pro_imperso_target__eafb14_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['started_at'], name='pro_imperso_started_7c13a0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemode',
            index=models.Index(fields=['is_active', 'scope'], name='pro_mainten_is_acti_e5b9bb_idx'),
        ),
    ]
