# Generated by Django 5.2.15 on 2026-06-04 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('can_create_client', 'Can Create Client'), ('can_edit_client', 'Can Edit Client'), ('can_delete_client', 'Can Delete Client'), ('can_create_operator', 'Can Create Operator'), ('can_assign_operator', 'Can Assign Operator'), ('can_create_assistant', 'Can Create Assistant'), ('can_edit_assistant', 'Can Edit Assistant'), ('can_disable_assistant', 'Can Disable Assistant'), ('can_impersonate', 'Can Impersonate'), ('can_manage_permissions', 'Can Manage Permissions'), ('can_manage_organizations', 'Can Manage Organizations')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions_permission',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRO_USER', 'Pro User'), ('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('CLIENT', 'Client'), ('ASSISTANT', 'Assistant')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.permission')),
            ],
            options={
                'db_table': 'permissions_role_permission',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_specific_permissions', to='permissions.permission')),
            ],
            options={
                'db_table': 'permissions_user_permission',
            },
        ),
    ]
