# Generated by Django 5.2.10 on 2026-02-27 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0032_cropper_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('print_list', 'Print List'), ('downloaded', 'Downloaded')], db_index=True, default='print_list', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to='core.idcard')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_requests', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to='core.idcardtable')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table', 'status'], name='cardprint_p_table_i_31f927_idx'), models.Index(fields=['table', 'status', '-created_at'], name='cardprint_p_table_i_96c2c2_idx'), models.Index(fields=['card'], name='cardprint_p_card_id_7cde6a_idx'), models.Index(fields=['created_at'], name='cardprint_p_created_1a229e_idx')],
            },
        ),
    ]
