# Generated by Django 5.2.10 on 2026-02-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printrequest',
            name='status',
            field=models.CharField(choices=[('print_list', 'Print List'), ('finalized', 'Finalized'), ('downloaded', 'Downloaded'), ('pool', 'Pool')], db_index=True, default='print_list', max_length=20),
        ),
    ]
