# Generated by Django 5.2.10 on 2026-02-27 19:55

from django.db import migrations, models


def migrate_downloaded_to_finalized(apps, schema_editor):
    """Move any existing 'downloaded' records to 'finalized' before removing the status."""
    PrintRequest = apps.get_model('cardprint', 'PrintRequest')
    PrintRequest.objects.filter(status='downloaded').update(status='finalized')


class Migration(migrations.Migration):

    dependencies = [
        ('cardprint', '0002_add_finalized_pool_status'),
    ]

    operations = [
        migrations.RunPython(migrate_downloaded_to_finalized, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='printrequest',
            name='status',
            field=models.CharField(choices=[('print_list', 'Print List'), ('finalized', 'Finalized'), ('pool', 'Pool')], db_index=True, default='print_list', max_length=20),
        ),
    ]
