# Generated by Django 5.2.10 on 2026-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprint', '0004_generate_list_cardtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='field_config',
            field=models.JSONField(blank=True, default=dict, help_text='Pre-selected fields per side: {"is_two_sided": bool, "front_fields": [...], "back_fields": [...]}'),
        ),
    ]
