# Generated by Django 5.2.10 on 2026-04-01 12:00

from django.db import migrations, models


def migrate_print_list_to_generate_list(apps, schema_editor):
    PrintRequest = apps.get_model('cardprint', 'PrintRequest')
    PrintRequest.objects.filter(status='print_list').update(status='generate_list')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cardprint', '0005_add_field_config_to_cardtemplate'),
    ]

    operations = [
        migrations.RunPython(migrate_print_list_to_generate_list, noop_reverse),
        migrations.AlterField(
            model_name='printrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('generate_list', 'Generate List'),
                    ('finalized', 'Finalized'),
                    ('pool', 'Pool'),
                ],
                db_index=True,
                default='generate_list',
                max_length=20,
            ),
        ),
    ]
