# Generated by Django 5.2.12 on 2026-04-10 11:48

import cardprint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprint', '0010_template_json_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='template_json',
            field=models.JSONField(blank=True, default=cardprint.models.default_template_json, help_text='Template-driven canvas data for field elements rendering.'),
        ),
    ]
