# Generated by Django 5.2.12 on 2026-04-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardprint', '0013_cardtemplate_production_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardTemplateDoc',
        ),
    ]
