# Generated by Django 5.2.15 on 2026-06-05 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0003_card_cards_card_version_938475_idx'),
        ('organizations', '0002_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('XLSX', 'XLSX'), ('ZIP', 'ZIP')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0.0)),
                ('record_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_sessions', to='organizations.organization')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_sessions', to='tables.table')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_results', to='cards.card')),
                ('export_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exports.exportsession')),
            ],
            options={
                'db_table': 'export_result',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=512)),
                ('stored_path', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='exports.exportsession')),
            ],
            options={
                'db_table': 'export_artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('export_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], default='PDF', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_templates_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='organizations.organization')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='tables.table')),
            ],
            options={
                'db_table': 'export_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exportsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_sessions', to='exports.exporttemplate'),
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='exports.exporttemplate')),
            ],
            options={
                'db_table': 'template_asset',
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='exports.exporttemplate')),
            ],
            options={
                'db_table': 'template_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='exporttemplate',
            index=models.Index(fields=['table'], name='export_temp_table_i_93a2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='exporttemplate',
            index=models.Index(fields=['organization'], name='export_temp_organiz_8d17bb_idx'),
        ),
        migrations.AddIndex(
            model_name='exportsession',
            index=models.Index(fields=['organization'], name='export_sess_organiz_2fd88b_idx'),
        ),
        migrations.AddIndex(
            model_name='exportsession',
            index=models.Index(fields=['table'], name='export_sess_table_i_7e0223_idx'),
        ),
        migrations.AddIndex(
            model_name='exportsession',
            index=models.Index(fields=['status'], name='export_sess_status_58cfd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateversion',
            unique_together={('template', 'version_number')},
        ),
    ]
