# Generated by Django 5.2.15 on 2026-06-08 04:06

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_card_reprint_count_card_total_print_count'),
        ('organizations', '0002_initial'),
        ('tables', '0002_table_card_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReprintRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('PRINTED', 'Printed')], default='REQUESTED', max_length=50)),
                ('draft_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('draft_media_changes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('request_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reprints', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_requests', to='cards.card')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reprint_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_requests', to='organizations.organization')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_reprints', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_reprints', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_requests', to='tables.table')),
            ],
            options={
                'db_table': 'reprints_reprint_request',
            },
        ),
        migrations.CreateModel(
            name='ReprintHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_history', to='cards.card')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reprint_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reprints.reprintrequest')),
            ],
            options={
                'db_table': 'reprints_reprint_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReprintExportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('download_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reprint_requests', models.ManyToManyField(related_name='export_sessions', to='reprints.reprintrequest')),
            ],
            options={
                'db_table': 'reprints_reprint_export_session',
            },
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['organization'], name='reprints_re_organiz_d101ad_idx'),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['table'], name='reprints_re_table_i_1a36dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['status'], name='reprints_re_status_e2a085_idx'),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['created_at'], name='reprints_re_created_c356e1_idx'),
        ),
    ]
