# Generated by Django 5.2.15 on 2026-06-04 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATE_CLIENT', 'Create Client'), ('DELETE_CLIENT', 'Delete Client'), ('CREATE_ASSISTANT', 'Create Assistant'), ('DELETE_ASSISTANT', 'Delete Assistant'), ('CREATE_OPERATOR', 'Create Operator'), ('ASSIGN_OPERATOR', 'Assign Operator'), ('PERMISSION_CHANGE', 'Permission Change'), ('IMPERSONATION', 'Impersonation')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditlogs_audit_log',
            },
        ),
    ]
