# Generated by Django 5.2.15 on 2026-06-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0003_alter_auditlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('CREATE_CLIENT', 'Create Client'), ('DELETE_CLIENT', 'Delete Client'), ('CREATE_ASSISTANT', 'Create Assistant'), ('DELETE_ASSISTANT', 'Delete Assistant'), ('CREATE_OPERATOR', 'Create Operator'), ('ASSIGN_OPERATOR', 'Assign Operator'), ('PERMISSION_CHANGE', 'Permission Change'), ('IMPERSONATION', 'Impersonation'), ('TABLE_CREATED', 'Table Created'), ('TABLE_UPDATED', 'Table Updated'), ('FIELD_CREATED', 'Field Created'), ('FIELD_UPDATED', 'Field Updated'), ('CARD_CREATED', 'Card Created'), ('CARD_UPDATED', 'Card Updated'), ('CARD_DELETED', 'Card Deleted')], max_length=50),
        ),
    ]
