# Generated by Django 5.2.15 on 2026-06-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0005_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('CREATE_CLIENT', 'Create Client'), ('DELETE_CLIENT', 'Delete Client'), ('CREATE_ASSISTANT', 'Create Assistant'), ('DELETE_ASSISTANT', 'Delete Assistant'), ('CREATE_OPERATOR', 'Create Operator'), ('ASSIGN_OPERATOR', 'Assign Operator'), ('PERMISSION_CHANGE', 'Permission Change'), ('IMPERSONATION', 'Impersonation'), ('TABLE_CREATED', 'Table Created'), ('TABLE_UPDATED', 'Table Updated'), ('FIELD_CREATED', 'Field Created'), ('FIELD_UPDATED', 'Field Updated'), ('CARD_CREATED', 'Card Created'), ('CARD_UPDATED', 'Card Updated'), ('CARD_DELETED', 'Card Deleted'), ('CARD_VERIFIED', 'Card Verified'), ('CARD_UNVERIFIED', 'Card Unverified'), ('CARD_APPROVED', 'Card Approved'), ('CARD_UNAPPROVED', 'Card Unapproved'), ('CARD_DOWNLOADED', 'Card Downloaded'), ('CARD_RESTORED', 'Card Restored'), ('BULK_WORKFLOW_ACTION', 'Bulk Workflow Action'), ('MEDIA_UPLOAD', 'Media Uploaded'), ('MEDIA_REPLACE', 'Media Replaced'), ('MEDIA_DELETE', 'Media Deleted'), ('JOB_START', 'Job Started'), ('JOB_COMPLETE', 'Job Completed'), ('JOB_FAIL', 'Job Failed')], max_length=50),
        ),
    ]
