# Generated by Django 5.2.15 on 2026-06-05 14:29

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('tables', '0002_table_card_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop_keys_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_api_keys', to='organizations.organization')),
            ],
            options={
                'db_table': 'desktop_api_key',
            },
        ),
        migrations.CreateModel(
            name='DesktopAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_access_logs', to='organizations.organization')),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='desktop_sync.desktopapikey')),
            ],
            options={
                'db_table': 'desktop_access_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DesktopSyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filters', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('card_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('downloaded_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_sessions', to='desktop_sync.desktopapikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_sync_sessions', to='organizations.organization')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desktop_sync_sessions', to='tables.table')),
            ],
            options={
                'db_table': 'desktop_sync_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='desktopapikey',
            index=models.Index(fields=['organization', 'is_active'], name='desktop_api_organiz_9cb6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopapikey',
            index=models.Index(fields=['key_hash'], name='desktop_api_key_has_08a8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopaccesslog',
            index=models.Index(fields=['api_key', 'event_type'], name='desktop_acc_api_key_c5ee72_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopaccesslog',
            index=models.Index(fields=['organization'], name='desktop_acc_organiz_26dc77_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopaccesslog',
            index=models.Index(fields=['timestamp'], name='desktop_acc_timesta_2c602b_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopsyncsession',
            index=models.Index(fields=['api_key'], name='desktop_syn_api_key_4a75fb_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopsyncsession',
            index=models.Index(fields=['status'], name='desktop_syn_status_65312f_idx'),
        ),
    ]
