# Generated by Django 5.2.15 on 2026-06-04 05:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='organizations.organization')),
            ],
            options={
                'db_table': 'tables_table',
                'indexes': [models.Index(fields=['organization'], name='tables_tabl_organiz_69fc3e_idx'), models.Index(fields=['name'], name='tables_tabl_name_afbb82_idx'), models.Index(fields=['status'], name='tables_tabl_status_9d1072_idx'), models.Index(fields=['is_deleted'], name='tables_tabl_is_dele_435d11_idx')],
            },
        ),
    ]
