# Generated by Django 5.2.15 on 2026-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='card_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
