# Generated by Django 5.2.15 on 2026-06-05 12:59

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0004_alter_card_status'),
        ('fields', '0002_initial'),
        ('organizations', '0002_initial'),
        ('tables', '0002_table_card_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_sessions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sandbox_session',
            },
        ),
        migrations.CreateModel(
            name='SandboxImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('warning_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sandbox_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='sandbox.sandboxsession')),
            ],
            options={
                'db_table': 'sandbox_import_session',
            },
        ),
        migrations.CreateModel(
            name='SandboxExportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('record_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sandbox_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_sessions', to='sandbox.sandboxsession')),
            ],
            options={
                'db_table': 'sandbox_export_session',
            },
        ),
        migrations.CreateModel(
            name='SandboxChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_changes', to='cards.card')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.field')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='sandbox.sandboxsession')),
            ],
            options={
                'db_table': 'sandbox_change',
            },
        ),
        migrations.CreateModel(
            name='SandboxCardStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_statuses', to='cards.card')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_statuses', to='sandbox.sandboxsession')),
            ],
            options={
                'db_table': 'sandbox_card_status',
            },
        ),
        migrations.CreateModel(
            name='SandboxCardDelete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_deletes', to='cards.card')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_cards', to='sandbox.sandboxsession')),
            ],
            options={
                'db_table': 'sandbox_card_delete',
            },
        ),
        migrations.CreateModel(
            name='SandboxCardCreate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cards', to='sandbox.sandboxsession')),
            ],
            options={
                'db_table': 'sandbox_card_create',
            },
        ),
        migrations.CreateModel(
            name='SandboxWorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_workflow_history', to='cards.card')),
                ('sandbox_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='sandbox.sandboxcardcreate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='sandbox.sandboxsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sandbox_workflow_history',
            },
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['user', 'device_id'], name='sandbox_ses_user_id_7a52be_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['token'], name='sandbox_ses_token_7ab5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['expires_at'], name='sandbox_ses_expires_51b7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['is_active'], name='sandbox_ses_is_acti_5b8351_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sandboxsession',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='sandboximportsession',
            index=models.Index(fields=['sandbox_session'], name='sandbox_imp_sandbox_3aa907_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboximportsession',
            index=models.Index(fields=['table'], name='sandbox_imp_table_i_11365c_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxexportsession',
            index=models.Index(fields=['sandbox_session'], name='sandbox_exp_sandbox_571082_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxexportsession',
            index=models.Index(fields=['table'], name='sandbox_exp_table_i_869da1_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxchange',
            index=models.Index(fields=['session', 'card'], name='sandbox_cha_session_09058c_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxchange',
            index=models.Index(fields=['session', 'table'], name='sandbox_cha_session_0053c4_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxchange',
            index=models.Index(fields=['timestamp'], name='sandbox_cha_timesta_c887c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sandboxchange',
            unique_together={('session', 'card', 'field')},
        ),
        migrations.AddIndex(
            model_name='sandboxcardstatus',
            index=models.Index(fields=['session'], name='sandbox_car_session_e896e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sandboxcardstatus',
            unique_together={('session', 'card')},
        ),
        migrations.AddIndex(
            model_name='sandboxcarddelete',
            index=models.Index(fields=['session'], name='sandbox_car_session_8061ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sandboxcarddelete',
            unique_together={('session', 'card')},
        ),
        migrations.AddIndex(
            model_name='sandboxcardcreate',
            index=models.Index(fields=['session', 'table'], name='sandbox_car_session_ad89f5_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxworkflowhistory',
            index=models.Index(fields=['session', 'card'], name='sandbox_wor_session_56c8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxworkflowhistory',
            index=models.Index(fields=['session', 'sandbox_card'], name='sandbox_wor_session_c22a8b_idx'),
        ),
    ]
