# Generated by Django 5.2.12 on 2026-04-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='mobile_app__platfor_b6561d_idx',
            old_name='mobile_app_m_platfor_d4a050_idx',
        ),
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='mobile_app__user_id_83df9e_idx',
            old_name='mobile_app_m_user_id_c59c27_idx',
        ),
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='mobile_app__user_id_e67e94_idx',
            old_name='mobile_app_m_user_id_b57c9a_idx',
        ),
    ]
