# Generated by Django 5.2.15 on 2026-06-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_537540_idx'),
        ),
    ]
