# Generated by Django 5.2.15 on 2026-06-05 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE_UPLOAD', 'Image Upload'), ('IMAGE_REPLACE', 'Image Replace'), ('IMAGE_DELETE', 'Image Delete'), ('IMPORT_XLSX', 'Import XLSX'), ('IMPORT_XLSX_ZIP', 'Import XLSX with Zip'), ('REUPLOAD_IMAGES', 'Reupload Images'), ('EXPORT_PDF', 'Export PDF'), ('EXPORT_DOCX', 'Export DOCX'), ('EXPORT_XLSX', 'Export XLSX'), ('EXPORT_ZIP', 'Export Zip')], max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('completion_metadata', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job')),
            ],
            options={
                'db_table': 'job_event',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.job')),
            ],
            options={
                'db_table': 'job_log',
                'ordering': ['created_at'],
            },
        ),
    ]
