# Generated by Django 5.2.15 on 2026-06-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tables.table'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['table'], name='fields_fiel_table_i_427f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['type'], name='fields_fiel_type_7ade28_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['is_deleted'], name='fields_fiel_is_dele_d4fcf1_idx'),
        ),
    ]
